#!/bin/sh
set -e

/usr/bin/psql -v ON_ERROR_STOP=1 --username postgres --dbname eventflow <<-EOSQL
       DROP TABLE IF EXISTS  "ReadModel-Account";
       CREATE TABLE IF NOT EXISTS "ReadModel-Account"
       (
           Id                          BIGINT GENERATED BY DEFAULT AS IDENTITY,
           AccountId  TEXT        NOT NULL,
           AggregateId VARCHAR(64) NOT NULL,
           TransferId VARCHAR(64),
           CreateTime                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
           UpdatedTime                 TIMESTAMPTZ NOT NULL DEFAULT NOW(),
           LastAggregateSequenceNumber INT       ,
           FirstName                   TEXT,
           LastName                    TEXT,
           Balance                     NUMERIC(18, 2)       DEFAULT 0,
           Currency                    TEXT,
           CONSTRAINT "PK_ReadModel-Account" PRIMARY KEY (Id)
       );
EOSQL